# Generated by Django 4.2.13 on 2024-06-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_quik', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_time',
            new_name='createtime',
        ),
    ]
