# Generated by Django 4.2.13 on 2024-06-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializer_quik', '0004_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64, verbose_name='标签')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='serializer_quik.tag', verbose_name='标签'),
        ),
    ]
